before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: ML4nO63k47NH3e/frFayEAy8CZJQ804CDOmdAq4XXZFlSKSYl7+l2a5h9bkrDK9WlbdZeJ/8VzT64NnSdLaZyit5AENzsTxOwyKeQVLE5g0MHgxwaySXhBcyi08y37RGULPm4mKKzhyK+hA/s20EMVUhTPk+xOsCFq2NPOCxKdthcogm8n/1/Fj+EBUz/a39BUWr+Wo3XnqIH4LbK6Xag3a+15acIbV+DzK0ErVNyANCw1aGNo4pGmpQHM66QOTRXS3m2m2EUT/XtCF0QHByISNbRZG2kFBzGwo+PfWcdELMLS3H9UIm+xA+jb4tDZEnQkmhg69JjLt7vH8sTscG9IwNVIWigqyI4L8CpYFJnCvB8e1VesR7KgLulGMarlW1vMCA0HxdK40x3yN8AUrlQxtnC5aJSuSqIX7KAfzDHrwTXBupuSK7GPnmb1I4YlYbshYQvWYiDuwsU9diRxZtkhj1zwnnXKyFrhh7Z5JlRaa6sweYNwDGqmplvlHm76j/88zz6Ac1Nu65niQLYmaBBemS5vApc9DroBk6/OE26nejzlAWX1peAcpPHJDsZ5LTqYvvAb2ekG5jOPeJekyb1+n4SpWP5n0ZpWRt8nbHL+jhRjJ+GLtW1fbh3Dx2PAJIvFIvAbuID0+aMxMQxBc7EHZoDdSswwKBohRXC+a1MW0= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
